version: 0.2
env:
  variables:
    PACKAGE_S3_BUCKET: 252-alram

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r src/requirements.txt

  build:
    commands:
      - echo "Building SAM application..."
      - sam build --template template.yml

  post_build:
    commands:
      - echo "Packaging SAM application..."
      - sam package --s3-bucket $PACKAGE_S3_BUCKET --output-template-file outputtemplate.yml --s3-prefix monitoring

artifacts:
  files:
    - outputtemplate.yml